export const ADMIN_AUTH_LOGIN_SUCCESS = "ADMIN_AUTH_LOGIN_SUCCESS";

export const ADMIN_AUTH_LOGOUT_SUCCESS = "ADMIN_AUTH_LOGOUT_SUCCESS";
export const ADMIN_GET_PRODUCT_SUCCESS = "ADMIN_GET_PRODUCT_SUCCESS";
export const ADMIN_GET_PRODUCT_FAILURE = "ADMIN_GET_PRODUCT_FAILURE";
export const ADMIN_GET_PRODUCT_LOADING = "ADMIN_GET_PRODUCT_LOADING";

export const PAGE_UPDATE = "PAGE_UPDATE"